use_frameworks!

platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'BOILocalTerminal_Example' do
  pod 'BOILocalTerminal', :path => '../'

  target 'BOILocalTerminal_Tests' do
    inherit! :search_paths

    
  end
end
