/* Copyright (C) 2017 by eService
 *
 * All rights reserved.  No part of this software may be reproduced,
 * transmitted, transcribed, stored in a retrieval system, or translated
 * into any language or computer language, in any form or by any means,
 * electronic, mechanical, magnetic, optical, chemical, manual or otherwise,
 * without the prior written permission of eService.
 */
/*
 * tags.hpp
 *
 *  Created on: 3 sty 2017
 *      Author: przemyslaw.ogorzalek
 */

#ifndef TAGS_HPP_
#define TAGS_HPP_

#ifdef __cplusplus
extern "C" {
#endif

typedef enum
{
    TAG_INVALID = 0x00,
    TAG_AID = 0x9F06,
    TAG_APP_LABEL = 0x50,
    TAG_APP_PREFERRED_NAME = 0x9F12,
    TAG_AMOUNT = 0x9F02,
    TAG_TRANSACTION_TYPE = 0x9C,
    TAG_AUTHORIZATION_CODE = 0x89,
    TAG_MID = 0x9F16,
    TAG_CARD_NUMBER = 0x5A,
    TAG_TRANSACTION_DATE = 0x9A,
    TAG_TRANSACTION_TIME = 0x9F21,
    TAG_ATC = 0x9F36,
    TAG_AC = 0x9F26,
    TAG_TVR = 0x95,
    TAG_TSI = 0x9B,
    TAG_TRANSACTION_CURRENCY = 0x5F2A,
    TAG_TERMINAL_CURRENCY = 0x5F3C,
    TAG_AMOUNT_IN_TERMINAL_CURRENCY = 0x9F3A,
    TAG_CASHBACK_AMOUNT = 0x9F03,
    TAG_VLP_LIMIT = 0x9F79,
    TAG_CURRENCY_EXPONENT = 0x5F36,
    TAG_TID = 0x9F1C,

    TAG_IN_REQUEST_TOKEN = 0xDF01,
    TAG_IN_BLIK_ENTERED_CODE = 0xDF02,
    TAG_IN_ADDITIONAL_PRINTOUT_DATA = 0xDF03,
    TAG_IN_VARIABLE_SYMBOL = 0xDF06,
    TAG_IN_SPECIFIC_SYMBOL = 0xDF07,
    TAG_IN_TRANSACTION_CURRENCY = 0xDF08,   
    TAG_IN_SUPPORTED_LANGUAGES = 0xDF09,
    TAG_IN_CASHIER_LANGUAGE = 0xDF0A,       
    TAG_IN_CARDHOLDER_LANGUAGE = 0xDF0B,    


    TAG_BLIK_REFERENCE_CODE = 0xDF01,
    TAG_BLIK_ENTERED_CODE = 0xDF02,
    TAG_CARD_TOKEN = 0xDF03,
    TAG_EMV_CRYPTOGRAM_TYPE = 0xDF04,
    TAG_CARD_EXPIRY_DATE = 0xDF05,
    TAG_ADDITIONAL_CARDSET_VALUE_1 = 0xDF06,
    TAG_ADDITIONAL_CARDSET_VALUE_2 = 0xDF07,
    TAG_ADDITIONAL_CARDSET_VALUE_3 = 0xDF08,
    TAG_ADDITIONAL_CARDSET_VALUE_4 = 0xDF09,
    TAG_ADDITIONAL_CARDSET_VALUE_5 = 0xDF0A,
    TAG_ADDITIONAL_TRANSACTION_FLAG = 0xDF0B,
    TAG_MASKED_PAN_FOR_CUSTOMER = 0xDF0C,
    TAG_ERZSEBET_VOUCHER_TYPE = 0xDF0D,
    TAG_ADDITIONAL_PRINTOUT_DATA_FROM_ECR = 0xDF11,
    TAG_AMOUNT_OF_TIP = 0xDF12,
    TAG_MARKUP = 0xDF14,
    TAG_MARKUP_TEXT = 0xDF15,
    TAG_MARKUP_INFO = 0xDF16,
    TAG_DCC_RATES_INFO = 0xDF17,
    TAG_VARIABLE_SYMBOL = 0xDF18,
    TAG_SPECIFIC_SYMBOL = 0xDF19,
    TAG_MERCHANT_COPY_LANGUAGE = 0xDF1A,
    TAG_CLIENT_COPY_LANGUAGE = 0xDF1B,
    TAG_MSP_DATA = 0xDF1C,
    TAG_MULTIMCC_DATA = 0xDF1D,
    TAG_CARDSET_NAME = 0xDF1E,

    TAG_TRANSACTION_ID = 0x9FD201,
    TAG_TOTAL_AMOUNT_SUM = 0x9FD202,
    TAG_BATCH_TRANSACTION_COUNT = 0x9FD203,
    TAG_BATCH_STATUS = 0x9FD204,
    TAG_ACQUIER_IDENTIFIER = 0x9FD205,
    TAG_BATCH_NUMBER = 0x9FD206,
    TAG_BATCH_DATE = 0x9FD207,
    TAG_BATCH_TIME = 0x9FD208,
    TAG_ACTIVATION_SEQUENCE_NUMBER = 0x9FD209,
    TAG_CASHIER_IDENTIFIER = 0x9FD20A,
    TAG_EVOUCHER_INFO = 0x9FD20B,
    TAG_RESET_REPORT = 0x9FD221,
    TAG_CARDSET_ID = 0x9FD222,
    TAG_SEQUENCE_NUMBER_FIRST_TRANSACTION = 0x9FD223,
    TAG_SEQUENCE_NUMBER_LAST_TRANSACTION = 0x9FD224,
    TAG_CURRENCY_ID = 0x9FD225,

    TAG_TRANSACTION_NUMBER = 0x9FD401,
    TAG_SERVER_ERROR_MESSAGE = 0x9FD402,
    TAG_USED_READER = 0x9FD403,
    TAG_AUTHORIZATION_MESSAGE_NUMBER = 0x9FD404,
    TAG_AUTHORIZATION_TYPE = 0x9FD405,
    TAG_TRANSACTION_REFERENCE_NUMBER = 0x9FD406,
    TAG_TRANSACTION_TITLE = 0x9FD407,
    TAG_EXCHANGE_RATE = 0x9FD408,
    TAG_DCC_TEXT_1 = 0x9FD409,
    TAG_DCC_TEXT_2 = 0x9FD40A,
    TAG_TRANSACTION_RETURN_CODE = 0x9FD40B,
    TAG_TRANSACTION_TO_COMPLETE = 0x9FD40C,
    TAG_TRANSACTION_TO_REVERSE = 0x9FD40D,
    TAG_REVERSAL_INDICATOR = 0x9FD40E,
    TAG_MASKED_PAN = 0x9FD450,
    TAG_AUTHORIZATION_METHOD = 0x9FD451,

    TAG_HANDLE_REQUESTS = 0x9FCD01,
    TAG_CONTINUE_PREVIOUS_TRANSACTION = 0x9FCD02,
    TAG_TERMINAL_ADDRESS_1 = 0x9FCD31,
    TAG_TERMINAL_ADDRESS_2 = 0x9FCD32,
    TAG_TERMINAL_ADDRESS_3 = 0x9FCD33,
    TAG_PROMPT_ID = 0x9FCD50,
    TAG_PROMPT_MIN_ENTRY_LEN = 0x9FCD51,
    TAG_PROMPT_MAX_ENTRY_LEN = 0x9FCD52,
    TAG_PROMPT_ALLOWED_CHARACTERS = 0x9FCD53,
    TAG_PROMPT_SPECIAL_CHARACTERS = 0x9FCD54,
    TAG_PROMPT_TEXT = 0x9FCD55,
    TAG_CASH_REGISTER_ID = 0x9FCD56,
    TAG_TERMINAL_INDEX = 0x9FCD69,
    TAG_ORIGINAL_TRANSACTION_TYPE = 0x9FD601,
    TAG_PRINTING_INDICATOR = 0x9FD801,
    TAG_RELATED_AUTHORIZATION_CODE = 0x9FD901,

    TAG_EV_OPERATION_TYPE              = 0x9FE001,
    TAG_EV_EAN                         = 0x9FE002,
    TAG_EV_OP_ID                       = 0x9FE003,
    TAG_EV_ECR_TRANSACTION_TYPE        = 0x9FE013,
    TAG_EV_TERMINAL_PRINTING_INDICATOR = 0x9FE014,
    TAG_EV_OPERATOR_NAME               = 0x9FE015,
    TAG_EV_COUPONS_VALUE_LABEL         = 0x9FE016,
    TAG_EV_SYSTEM_MESSAGES             = 0x9FE017,
    TAG_EV_COUPON_TYPE_ID              = 0x9FE018,
    TAG_EV_COUPON_SERIAL_NUMBER        = 0x9FE019,
    TAG_EV_COUPON_VALUE                = 0x9FE01A,
    TAG_EV_COUPON_CODE                 = 0x9FE01B,
    TAG_EV_COUPON_PARAM1               = 0x9FE01C,
    TAG_EV_COUPON_PARAM2               = 0x9FE01D,
    TAG_EV_BARCODE                     = 0x9FE01E,
    TAG_EV_COUPON_PARAM4               = 0x9FE01F,
    TAG_EV_COUPON_PARAM5               = 0x9FE021,
    TAG_EV_SELL_TYPE                   = 0x9FE022,
    TAG_EV_COPY_INDICATOR              = 0x9FE023,
    TAG_EV_STAN                        = 0x9FE024,
    TAG_EV_TRX_DATE_TIME               = 0x9FE025,
    TAG_EV_LOGIN_MODE                  = 0x9FE026,
    TAG_EV_CASHIER_LOGIN               = 0x9FE027,
    TAG_EV_OPERATOR_ID                 = 0x9FE028,
    TAG_EV_PAYMENT_MODE                = 0x9FE029,
    TAG_EV_COUPON_CONFIRMATION         = 0x9FE02A,
    TAG_EV_OP_TEMPLATE                 = 0x9FE02B,

    TAG_FLEET_CARD_TAG_ITEM_ID = 0xDF01,
    TAG_FLEET_CARD_TAG_PRODUCT_CODE = 0xDF02,
    TAG_FLEET_CARD_TAG_AMOUNT = 0xDF03,
    TAG_FLEET_CARD_TAG_UNIT_MEASURE = 0xDF04,
    TAG_FLEET_CARD_TAG_UNIT_PRICE = 0xDF05,
    TAG_FLEET_CARD_TAG_QUANTITY = 0xDF06,
    TAG_FLEET_CARD_TAG_TAX_CODE = 0xDF07,

    TAG_FLEET_CARD_TAG_FLAGS = 0xDF01,
    TAG_FLEET_CARD_TAG_PRODUCT_NAMES = 0xDF02,
    TAG_FLEET_CARD_TAG_VEHICLE_NR = 0xDF03,
    TAG_FLEET_CARD_TAG_DRIVER_NR = 0xDF04,
    TAG_FLEET_CARD_TAG_MILEAGE = 0xDF05,
    TAG_FLEET_CARD_TAG_CAR_REGISTRATION_NR = 0xDF06,
    TAG_FLEET_CARD_TAG_UNIT_NR = 0xDF07,
    TAG_FLEET_CARD_TAG_ADDITIONAL_DATA = 0xDF08,
    TAG_FLEET_CARD_TAG_CAR_REPLACEMENT_INDICATOR = 0xDF09,
    TAG_FLEET_CARD_TAG_CAR_DRIVER_CODE = 0xDF0A,

    TAG_MSP_TAG_ACCOUNT_TYPE = 0xDF01,
    TAG_MSP_TAG_AMOUNT_TYPE = 0xDF02,
    TAG_MSP_TAG_AMOUNT = 0xDF03,
    TAG_MSP_TAG_LABEL = 0xDF04,
    TAG_MSP_TAG_TITLE_LIST = 0xDF05,

    // !!! only for internal use
    TAG_CONSTRUCTED_FLEET_CARD_SALE_ITEM_LIST = 0x7F01,
    TAG_CONSTRUCTED_FLEET_CARD_SALE_ITEM = 0x7F01,
    TAG_CONSTRUCTED_OUT_FLEET_CARD_PRODUCT_LIST = 0x7F01,
    TAG_CONSTRUCTED_OUT_FLEET_CARD_DATA = 0x7F02,
    TAG_CONSTRUCTED_MSP_ITEM_LIST = 0x7F02,
    TAG_CONSTRUCTED_MSP_ITEM = 0x7F01

} TlvTag;

#ifdef __cplusplus
}
#endif
#endif /* TAGS_HPP_ */
